name: Run Anaconda Setup Script for Mac Intel

on: [push, pull_request]

jobs:
  setup-env:
    runs-on: macOS-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set execute permissions on the script
      run: chmod +x quant_stack_setup_mac_310.sh

    - name: Execute the Anaconda setup script
      run: ./quant_stack_setup_mac_310.sh

    - name: Verify Installation
      run: |
        conda --version
        python --version