name: Run Anaconda Setup Script for Windows

on: [push, pull_request]

jobs:
  setup-env:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute the Anaconda setup script
      run: .\quant_stack_setup_windows_310.bat

    - name: Verify Installation
      run: |
        conda --version
        python --version
      shell: cmd
