name: Setup Anaconda Environment for Windows

on: [push, pull_request]

jobs:
  setup-env:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Anaconda (Windows)
      run: |
        choco install anaconda3 --yes
        echo "C:\tools\anaconda3\Scripts" >> $env:GITHUB_PATH
        echo "C:\tools\anaconda3" >> $env:GITHUB_PATH

    - name: Update Anaconda
      run: |
        conda update -n base -c conda-forge conda

    - name: Verify Anaconda Installation
      run: |
        conda --version
        python --version

    - name: Set Up Cache for Conda Packages
      uses: actions/cache@v2
      with:
        path: |
          C:\tools\anaconda3\pkgs
        key: windows-conda-${{ hashFiles('**/quant-stack-3-10-env.yaml') }}

    - name: Download conda-3-10-env.yaml from URL
      run: |
        Invoke-WebRequest -Uri https://raw.githubusercontent.com/jasonstrimpel/quant-stack/main/quant-stack-3-10-env.yaml -OutFile quant-stack-3-10-env.yaml

    - name: Create my_quant_lab Virtual Environment
      run: |
        conda env create -n quant_lab --file quant-stack-3-10-env.yaml

    - name: Activate and Use Conda Environment
      shell: cmd
      run: |
        call C:\tools\anaconda3\Scripts\activate my_quant_lab

    - name: Activate my_quant_lab Virtual Environment
      run: |
        conda activate quant_lab

    - name: Install Additional Stack Packages
      run: |
        pip install pyfolio-reloaded==0.9.5 alphalens-reloaded==0.4.3 quantstats==0.0.62 --no-deps
        pip install zipline-reloaded==3.0.3
        pip uninstall bottleneck -y